### ISSUE TITLE
A problem about utils.py.

### ISSUE THREAD

**Issue by hychong1997** [lrhammond/almanac#2]

**Comment by hychong1997** [comment]
In utils.py at line 105 there is an error that 'name 'range_actors' is not defined'.

**Comment by lrhammond** [comment]
Hi! Sorry for incredibly slow reply. I believe that this bug should now be fixed on [the 'overcooked_experiments' branch](https://github.com/lrhammond/almanac/tree/overcooked_experiments). The code on this branch is a bit less polished but a bit more up to date. Let me know if you have any other questions or difficulties when using it. You can also [email me](mailto:lewis.hammond@cs.ox.ac.uk) if that's easier. Thanks!
